name: tbep
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    restart: 'always'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_dbms_security_procedures_unrestricted=gds*
      # Volumes to be used need to be customized accordingly, this is just for myself
    volumes:
      - ./scripts:/var/lib/neo4j/import/
      - ../neo4j/data:/var/lib/neo4j/data
      - ./plugins:/var/lib/neo4j/plugins

  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: ghcr.io/mizzoudbl/tbep-frontend
    ports:
      - "3000:80"
    profiles: ["dev"]

  frontend:
    # Build option is not made available here as this breaks some css in the frontend
    # when built inside docker container, you can modify the compose yaml 
    # or use `docker build` command to build the image locally
    image: ghcr.io/mizzoudbl/tbep-frontend
    container_name: frontend
    restart: 'always'
    ports:
      - "3000:80"

  gsea:
    build: 
      context: gsea
      dockerfile: Dockerfile
    image: ghcr.io/mizzoudbl/tbep-gsea
    container_name: gsea
    restart: 'always'
    ports:
      - "5000:5000"
  
  nestjs:
    build:
      context: backend
      dockerfile: Dockerfile
    image: ghcr.io/mizzoudbl/tbep-nestjs
    container_name: nestjs
    # Change this if running on local to avoid restarting on failure
    restart: 'always'
    ports:
      - "4000:4000"
    depends_on:
      - neo4j
      - redis
    env_file:
      - backend/.env
  
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: 'always'
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/data

volumes:
  redis-cache: